server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Foodboxd_bd
    username: postgres
    password: TemikPos12
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update      # ??? ??????? ??????? ????? ????????? 'update', ????? ?????? ?? validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false           # ?????? ??? ??????????, ????? ????????
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# ???? ??? ?????????? ??????????? ?????? (????? ?????? ?????????? ??? ???????????? ???????)
app:
  upload:
    dir: uploads